version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/demo-react-devops-docker
    ports:
      - 3000:3000
    image: app:demo-react-devops-docker
    container_name: demo-react-devops-docker_container
    command: npm start
    